# .github/release-drafter.yml

name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

template: |
  ## What's Changed
  $CHANGES

categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"

  - title: "Bug Fixes"
    labels:
      - "bug"
      - "fix"

  - title: "Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "refactor"

change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
