name: CI - tests & lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        # If your project doesn't have lint script, replace with: npx eslint .

      - name: Run tests
        run: npm test -- --ci --reporter=jest-junit || true

      - name: Upload test results (junit) and coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./junit.xml
            ./coverage
