name: Scheduled maintenance

on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC (adjust as needed)
  workflow_dispatch: {} # lets you run it manually from Actions UI

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run maintenance script
        run: npm run maintenance || echo "No maintenance script defined"
      
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: maintenance-logs
          path: ./maintenance.log || ./logs
